# Generated by Django 5.1.3 on 2025-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0005_remove_taskcategory_description'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='TaskCategory.taskcategory'),
        ),
    ]
