# Generated by Django 5.1.3 on 2025-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0002_remove_task_category_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=100),
        ),
    ]
