# Generated by Django 5.1.3 on 2025-05-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0003_alter_taskcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='name',
            new_name='task_name',
        ),
    ]
