# Generated by Django 5.1.3 on 2025-05-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0004_rename_name_taskcategory_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='description',
        ),
    ]
