# Generated by Django 5.1.3 on 2025-04-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_album_musician'),
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Musician.musician'),
        ),
    ]
